# Meta
description: Hello, world!
keywords: zhiqing,java,android,志青
site_desc: Hello, world!

# Navigation
navigation:
- name: 主页
  slug: home
  url: /
- name: 归档
  slug: archives
  url: /archives
- name: 工作
  slug: studio
  url: http://studio.zhiqing.info
- name: 关于
  slug: about
  url: /about

# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics:
favicon: /images/avatar.png
author_url: http://zhiqing.info

# Less
less:
  compress: true


# use url, not username
social:
- slug: email
  url: mailto:i@zhiqing.info
- slug: github
  url: https://github.com/zhiqing-lee
- slug: twitter
  url: https://twitter.com/zhiqing_hello
- slug: rss
	url: /atom.xml
- slug: google
  url: #https://plus.google.com/+ArtChenOtakism/posts
- slug: facebook
  url: # https://www.facebook.com/zanchoret
- slug: linkedin
  url: # https://www.linkedin.com/in/buzun
- slug: sina-weibo
  url: #http://weibo.com/otakism/
- slug: tumblr
  url: # http://artchen.tumblr.com
- slug: dribbble
  url: # https://dribbble.com/artchen
- slug: pinterest
  url: # https://www.pinterest.com/otakism/
- slug: instagram
  url: # https://instagram.com/otakism/
- slug: behance
  url: # https://www.behance.net/artchen
